import Head from 'next/head'
import Container from '../components/Container'
export default function Home() {
  return (<div>
    <Container>
    <Head>
      <title>My Portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    </Container>
  </div>
  )
}
